# Generated by Django 5.1.2 on 2024-11-02 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='VideoGameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('Release_Date', models.DateField(verbose_name='Release date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.authormodel', verbose_name='Author')),
            ],
        ),
    ]
