# Generated by Django 5.1.2 on 2024-11-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_videogamemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogamemodel',
            options={'verbose_name': 'Video Game', 'verbose_name_plural': 'Video Games'},
        ),
        migrations.AlterModelTable(
            name='videogamemodel',
            table='Video Games',
        ),
    ]
